# Generated by Django 2.2.6 on 2019-12-28 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20191228_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='FLOPS',
        ),
        migrations.AlterField(
            model_name='processor',
            name='Add_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 19, 26, 8, 103572, tzinfo=utc)),
        ),
    ]
